### PR TITLE
Add Linux Notification Support

### PR DESCRIPTION
**Pull request by josephnglynn**
This mr adds a shared implementation for native code (c++ linux and windows) in native directory, as well as an almost complete implementation for linux and implements the required flutter code for windows but not the platform specific code.

Originally I planned to submit this mr with a working windows notification implementation as well however after two days going crazy trying to work out notifications in a windows VM and me myself not using windows I have decided to leave it for someone else crazy enough to try and wrangle through microsoft's documentation.

For anyone in the future trying to implement notifications on windows - I managed to get notifications to show similar to what is seen below on linux with winrt and its toast notifications, however I couldn't figure out how to update the notification after it was posted, and the CMakeList.txt file and actual code was  "janky".

The linux implementation is almost complete as it lacks alarm / vibration support due to shared preferences not seeming to work and lacks an AlarmManager like implementation. Instead the notification is checked for update every 1000 / 60 ms and in that loop it checks if the timer has expired so at most it would be off by 1000 / 60 ms. If more accuracy is needed there is some kernel function calls and / or SIGALARM but I thought that might have been overkill.

Unfortunately I couldn't seem to get a progress bar.

Examples below using various Notification daemons e.g. dunst, xfce, mate

example1
example2
example3
example4
example5
example6

### CODE REVIEW

**Comment by brandonp2412** [comment]
Crazy work mate really well done. I think i'll look into how to play sounds before merging since the main point of an alarm is being notified at the end.

**Comment by brandonp2412** [comment]
As for shared preferences errors, I was actually considering removing them and just using drift sqlite for everything (1db instead of 2). Thoughts on me doing that? It means backups/imports of entire DB includes settings (which is getting large now).

**Comment by brandonp2412** [comment]
Haha I said that, checked out the branch, and did a bunch of work that now depends on your structure so i guess im including it!

**Comment by josephnglynn** [comment]
> As for shared preferences errors, I was actually considering removing them and just using drift sqlite for everything (1db instead of 2). Thoughts on me doing that? It means backups/imports of entire DB includes settings (which is getting large now).

It was pretty useful in Massive especially when debugging, so that sounds like a great idea.

As for the sound originally I was thinking of using something like ffmpeg, but seeing that audioplayers is already a dependency and it has a linux [implementation](https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers_linux) which is currently being linked to the final executable, it might be better to play via that.

**Pull request merged**
