### PR TITLE
Add alarm manager

### PR DESCRIPTION
**Pull request by josephnglynn**
8ca80ce5348cb7a9731d6ad189e14a203d325f25 Fixes gradle wanting signing certificates when building debug builds.

0dd37c1bec0481385b6b5cb9e9135b80d7108978 Fixes `Looking up a deactivated widget's ancestor is unsafe.`. This can only be caught in debug builds as the check is removed for release builds. See [here](https://github.com/flutter/flutter/blob/ae97ccd45393baf3d81e3b15d7b81aad52107adc/packages/flutter/lib/src/widgets/framework.dart#L4740) and [here](https://github.com/rrousselGit/provider/issues/679) for more information. This commit also removes listeners and some state variables in exchange for `context.watch<T>()` as recommanded in `Provider` [docs ](https://pub.dev/packages/provider)for reading values. 

cf353072eb149999aecc11125a85c669f187e43a Adds changes from [`https://gitea.presley.nz/brandon.presley/Massive/pulls/236`](https://gitea.presley.nz/brandon.presley/Massive/pulls/236) and adapts them to work with here.

ad728761beef3d616527925f2999ddcfeaca0fa8 Makes `TimerService` send a timeStamp with any command to the App UI, to keep them in sync.

731ff63a262387059e20c1ab32a0c4fca17c27b8 Makes App UI send a timeStamp with any command to `TimerService`, to keep them in sync + cleans up permission checks and methods.

b294b555211f927e1533794b2d5ab12569eb9b9a Fixes a UI bug causing discrepancies in the notification and UI timer + stops `TimerService` sending timer information to App UI if the App UI triggered the timer.

7ea4ec12074459fcad2ffd0421d08378d95949d7 Fixes if the previous commands in `Runnable` took long enough that `(timeTaken + timer.getRemainingMillis() % 1000) > 1000` then we could miss a second where we should've updated the timer. Also fixes the vibrate timer not turning off sometimes.

I have left the `getProgress` method in MainActivity, and `StopAlarm.kt` which can both be safely removed if there are no future plans for them.

If you want me to squash these some commits together let me know.

### CODE REVIEW

**Comment by josephnglynn** [comment]
I think this mr is feature complete now.

**Comment by josephnglynn** [comment]
This mr should now be feature complete.

**Comment by brandonp2412** [comment]
Seems to have an error when attempting to run:

```
PS C:\Users\brandon\flexify> flutter run
Resolving dependencies... (7.3s)
  _fe_analyzer_shared 64.0.0 (67.0.0 available)
  analyzer 6.2.0 (6.4.1 available)
  csv 5.1.1 (6.0.0 available)
  dart_style 2.3.4 (2.3.6 available)
  drift 2.15.0 (2.16.0 available)
  drift_dev 2.15.0 (2.16.0 available)
  ffi 2.1.0 (2.1.2 available)
  flutter_lints 2.0.3 (3.0.1 available)
  flutter_local_notifications 16.3.2 (17.0.0 available)
  js 0.6.7 (0.7.1 available)
  lints 2.1.1 (3.0.0 available)
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.11.0 available)
  meta 1.10.0 (1.12.0 available)
  path 1.8.3 (1.9.0 available)
  provider 6.1.1 (6.1.2 available)
  sqlparser 0.34.0 (0.34.1 available)
  test_api 0.6.1 (0.7.0 available)
  web 0.3.0 (0.5.1 available)
  web_socket_channel 2.4.0 (2.4.4 available)
  win32 5.2.0 (5.3.0 available)
Got dependencies!
21 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib\main.dart on Pixel 5 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     C:\Users\brandon\flexify\build\app\intermediates\packaged_manifests\debug\AndroidManifest.xml:71: error: 'specialUse' is incompatible with attribute foregroundServiceType (attr) flags [camera=64, connectedDevice=16, dataSync=1, location=8, mediaPlayback=2, mediaProjection=32, microphone=128, phoneCall=4].
     error: failed processing manifest.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Running Gradle task 'assembleDebug'...                             12.0s
Exception: Gradle task assembleDebug failed with exit code 1
PS C:\Users\brandon\flexify> 
```

**Comment by brandonp2412** [comment]
It was a local environment error. I needed to change:
`C:\tools\flutter\packages\flutter_tools\gradle\src\main\groovy`
    static int compileSdkVersion = 33
 to 34.
 
 Great work as per usual King. Thanks a lot.

**Comment by brandonp2412** [comment]
@josephnglynn any idea what I should do about this?
I had the debug build sign with the release config because flutter run will forcibly uninstall + reinstall the app and wipe all my data if i accidentally forget to export my sets before running it.

**Comment by brandonp2412** [comment]
> @josephnglynn any idea what I should do about this? I had the debug build sign with the release config because flutter run will forcibly uninstall + reinstall the app and wipe all my data if i accidentally forget to export my sets before running it.

Scratch that I figured it out here:

https://github.com/brandonp2412/Flexify/commit/1121f3db1c1d15a0bb84998d1d927b29a338fb3d

**Pull request merged**
