### PR TITLE
Make set progress bars fade

### PR DESCRIPTION
**Pull request by dqnne**
Small design change to make the set progress bars fade in and out instead of whatever they are doing currently. I think a simple fade looks better for our purposes. Feel free to close if you disagree of course

### CODE REVIEW

**Comment by brandonp2412** [comment]
Can you make it instead animate from left to right like a progress bar? I kind of like the way it looks right now better than the fading

**Comment by brandonp2412** [comment]
Also I love you work and thanks for the contributions

**Comment by dqnne** [comment]
For sure, I can try that. Maybe close this and I'll open a new PR, or we rename this? Not sure what's best.

No problem, it's fun to contribute when I use the app myself. This is also the first project I've ever contributed to so it's good practice

**Comment by dqnne** [comment]
I'll close and open a new one soon

**Pull request closed without merging**
